spring:
  application:
    name: identity-server
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8085/}

keycloak:
  auth-server-url: http://localhost:8180
  realm: master
  resource: admin-cli
  ssl-required: none
  token-uri: http://localhost:8180/realms/master/protocol/openid-connect/token
  client-secret: y3zd3DSaYxec0oZdApPVb5JsNgPGDnJy
  client-id: admin-cli

