server:
  port: 8087
  servlet:
    context-path: /ocpp-mock-server
spring:
  application:
    name: ocpp-mock-server
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8081/}